### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by imcodingideas** [zero-to-mastery/travel-guide#108]
Browsing: https://zero-to-mastery.github.io/travel-guide/ I see a white screen. I can see the repo has a ton of extra `index*.html`files.

Can I fix this, as well as remove all the extra code?

**Comment by MattCSmith** [comment]
Hey @imcodingideas,
Fixing the white screen would be awesome, feel free to go ahead with this :)

As for removing all of the index file, I don't see a problem with this, but maybe @SamirJouni could confirm?

Regards,
Matt

**Comment by Toro2018** [comment]
I think the URL has linked to wrong file, 
on my own repository, after linking to the master branch, the page appeared and it looks much better than blank page. while I don't have the setting access to this master repository. 
[https://toro2018.github.io/travel-guide/](https://toro2018.github.io/travel-guide/)
I agree with @imcodingideas, it's called **Broken windows theory**, everyone keeps adding mess to this "travel guide", hope we can make it better ;) @SamirJouni

**Comment by MattCSmith** [comment]
White screen issue has been resolved, closing this issue.
