### ISSUE TITLE
Trash files

### ISSUE THREAD

**Issue by Jerry141** [zero-to-mastery/travel-guide#136]
Hello, 

I am quite new here and I really would love to participate to this project. Although in repo I see a lot of files that are not needed like bunch of index*.html files, lots of folders etc. Can we do something about that so project is more readable to newcomers like me? Right now I really do not have idea which index is valid and we should work on. 
Also there is white screen and different things are on "index.html" and on live-server from package.json.

Can we please do something about that? I think it is god practise to work in clear env, even if it is only playground, just to make good habits.

**Comment by Dromediansk** [comment]
Hi,
I had the same problem with recognition, which file is right. Check the Readme.md file for instructions, I suppose the most actual version is in "src" folder and written in React.

I would suggest to put non-actual files in one folder to let people know, which files are necessary and which are not.
