### ISSUE TITLE
Cannot run npm install

### ISSUE THREAD

**Issue by Pvanloon1983** [zero-to-mastery/travel-guide#505]
Hi,

I cloned this project, opened my terminal, got into the folder and tried the command: npm run install but it did not work. It gave the following error log:

(What do I have to do to solve this problem?)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose stack Error: missing script: install
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:364:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd C:\Users\vanlo\OneDrive\the-complete-web-developer-in-2019\Section 16\TravelGuide\travel-guide
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "install"
8 verbose node v10.15.1
9 verbose npm  v6.4.1
10 error missing script: install
11 verbose exit [ 1, true ]

**Comment by SudeepaGo** [comment]
Hi @Pvanloon1983 ,

**npm run script-name** is used to run the custom scripts which are defined in the scripts property in package.json. So when you run the command **npm run install**, it searches for a script named "install" and as it does not find one, it throws the error missing script: install

To install all the required packages you just need to do **npm install**

**Comment by Pvanloon1983** [comment]
Hi @SudeepaGo,

Thank you for your answer.

If I just need to put: **npm install** in the terminal and then press enter, why is it written as follows in the readme file: (It is a little bit confusing)

Clone(fork) this repository
Run these following commands on your terminal/ cmd prompt:
cd travel-guide
npm run install
npm run start
enter [http://localhost:3000] in your browser

**Comment by SudeepaGo** [comment]
@Pvanloon1983

Yeah, you are right. I think there must have been some mistake in the readme file.

**Comment by famebyproxy** [comment]
Glad I wasn't the only one running into this :)
