### ISSUE TITLE
What..?

### ISSUE THREAD

**Issue by orionseye** [zero-to-mastery/travel-guide#628]
...is this app all about?
I only see flags and some stats..where are activities? :)

**Comment by mcflav** [comment]
> ...is this app all about?
> I only see flags and some stats..where are activities? :)

I have the same question. I forked the project to see if maybe I can work on adding a page that shows the activities, and I see links in the project that should take you to an activities pages for a few cities within the country, but none of these are displayed when you run the application and view it in the browser? Seems to be a bug, unless the I need to do something outside of the instructions to launch the program?

**Comment by mcflav** [comment]
I think the issue is "Dead Links" after reading other issues posted. I will try to work on fixing a dead link.
