### ISSUE TITLE
Adding maps 

### ISSUE THREAD

**Issue by tjtalhaa** [zero-to-mastery/travel-guide#629]
Hey Authors and admins!

I was wondering if I add vector map of the country with other details on country page. Wouldn't that be awesome?

I am new here and I hadn't gone through the code yet thus I was curious to know about if this is possible in the first place?

**Comment by peter-wong-cy** [comment]
Hi all

It is cool to have the world map with travel info on top of it.  We can use the free map API like 'OpenLayers'.

I am new in here too.  Can I do some contribution on this part?

Cheers.
